name: Run Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.poetry/bin:$PATH"
        poetry install

    - name: Add Poetry to PATH
      run: echo "::add-path::$(poetry config bin -n --no-interaction)"

    - name: Run linting script
      run: |
        task lint_flake